
CXX = labFaPromptDriver.cpp
CXX += QueueClass.cpp
CXX += QueueClass.hpp
CXX += StackClass.cpp
CXX += StackClass.hpp


labFa: labFaPromptDriver.cpp QueueClass.cpp QueueClass.hpp StackClass.cpp StackClass.hpp
	g++ -std=c++0x labFaPromptDriver.cpp QueueClass.cpp StackClass.cpp -o staque


clean:
	rm staque


